---

- name: start docker
  service:
    name: docker
    state: started
  listen: "restart docker"

- name: reload docker
  service:
    name: docker
    state: reloaded
  listen: "reload docker"
