---

- name: restart docker
  service:
    name: docker
    state: restarted
  listen: "restart docker"

- name: reload docker
  service:
    name: docker
    state: reloaded
  listen: "reload docker"
